---
roles:
  - name: geerlingguy.dotfiles
  - name: geerlingguy.homebrew
  - name: geerlingguy.mas

collections: []
# Contains osx_defaults, which due to staleness does not support dict/dict-add
# - name: community.general
