---
- name: Install dockutil
  homebrew:
    name: dockutil
    state: present
  notify:
    - Clear homebrew cache

- name: Remove unwanted dock items
  ansible.builtin.include_tasks: tasks/dock-rm.yml
  loop: "{{ dockitems_to_remove }}"

- name: Ensure required dock items exist
  ansible.builtin.include_tasks: tasks/dock-add.yml
  loop: "{{ dockitems_to_persist }}"

- name: Ensure correct dock order
  ansible.builtin.command:
    cmd: dockutil --move '{{ item.name }}' --position {{ item.position }}
  when:
    - item.position is defined
    - item.position > 0
  loop: "{{ dockitems_to_persist }}"
