---
- name: Find if {{ item }} in dock
  ansible.builtin.command:
    cmd: dockutil --find '{{ item }}'
  register: dockitem_exists
  changed_when: false
  failed_when: '"No such file or directory" in dockitem_exists.stdout'
  tags: ['dock']

- name: Remove {{ item }} from dock
  ansible.builtin.command:
    cmd: dockutil --remove '{{ item }}'
  when: dockitem_exists.rc  == 0
  tags: ['dock']
