---
- name: find if {{ item }} in dock
  ansible.builtin.command:
    cmd: dockutil --find '{{ item.name }}'
  register: dockitem_exists
  changed_when: false
  failed_when: '"No such file or directory" in dockitem_exists.stdout'
  tags: ['dock']

- name: Add {{ item }} to dock
  ansible.builtin.command:
    cmd: dockutil --add '{{ item.path }}'
  when: dockitem_exists.rc > 0
  tags: ['dock']
