---
- name: "Install VS Code extensions"
  command: "code --install-extension '{{ item }}'"
  loop: "{{ vscode_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
